sudo: required
language: ruby
rvm:
  - 2.3.1
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
before_script:
  - psql -c 'create database my_app_test' -U postgres
bundler_args: --binstubs=./bundler_stubs